import Head from "next/head";
import Header from "../components/Header";

export default function Home() {
  return (
    <div>
      <h1 className="">
        <Head>
          <title>Watch with Hulu</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header></Header>
      </h1>
    </div>
  );
}
